threads:
    default: 1
    nanoplot: 4
    chopper: 4
    fastplong: 4
    flye: 12
    kraken2: 4
    multiqc: 4
    medaka: 8
    quast: 4
    checkm: 4
    parsing: 4
    busco: 4
    genome_size: 16
    canu: 18
    miniasm: 8
    necat: 8
    nextdenovo: 8
    raven: 8
    skani: 1
    autocycler_compress: 4

mem_gb:
    default: 4
    nanoplot: 32
    chopper: 8
    fastplong: 12
    flye: 240
    kraken2: 80
    multiqc: 32
    medaka: 20
    quast: 32
    checkm: 32
    parsing: 32
    busco: 16
    genome_size: 256
    canu: 432
    miniasm: 128
    necat: 128
    nextdenovo: 96
    raven: 128
    skani: 100
    autocycler_compress: 16
    
run_time_minutes:
    default: 30
    chopper: 30
    genome_size: 60
    canu: 600
    miniasm: 60
    necat: 60
    nextdenovo: 60
    raven: 60
    flye: 60
    autocycler_compress: 60
