threads:
    default: 1
    nanoplot: 4
    chopper: 4
    fastplong: 4
    flye: 12
    kraken2: 4
    multiqc: 4
    medaka: 8
    quast: 4
    checkm: 4
    parsing: 4
    busco: 4
    genome_size: 8
    canu: 18
    miniasm: 8
    necat: 4
    nextdenovo: 8
    raven: 8

mem_gb:
    default: 4
    nanoplot: 8
    chopper: 8
    fastplong: 12
    flye: 20
    kraken2: 20
    multiqc: 8
    medaka: 20
    quast: 8
    checkm: 8
    parsing: 8
    busco: 4
    genome_size: 8
    canu: 24
    miniasm: 16
    necat: 12
    nextdenovo: 12
    raven: 16

run_time_minutes:
    default: 30
    chopper: 30
    genome_size: 60
    canu: 600
    miniasm: 60
    necat: 60
    nextdenovo: 60
    raven: 60